### ISSUE TITLE
How Do I Make My Images Responsively Resize?

### ISSUE THREAD

**Issue by AGraphicDesigner** [Vestride/Shuffle#78]
Could you explain how to make images responsively resize, while keeping their aspect ratio, like in your <a href="http://vestride.github.io/Shuffle/images/">demo</a>.

Here is a reduced test case of my page:
http://codepen.io/anon/pen/XbNMYJ

And here is my full webpage: <a href="http://ajsdesign.net/">http://ajsdesign.net/</a>
I am using media queries as a workaround, but the result is far from ideal.

**Comment by Vestride** [comment]
The idea is you have a parent element which has the same ratio as your image. That way when your image loads, nothing around it needs to be re-adjusted.

```html
<div class="aspect">
  <div class="aspect-inner">
    <img src="foo.jpg">
  </div>
</div>
```

```css
.aspect {
  position: relative;
  width: 100%;
  height: 0;
  overflow: hidden;
  padding-bottom: 100%;
}

.aspect-inner {
  position: absolute;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
}

.aspect-16x9 {
  padding-bottom: 56.25%;
}
```

I then have images not exceed the width of their containers with `max-width`.

```css
img {
  max-width: 100%;
}
```

Does that answer your question?
