### ISSUE TITLE
Shuffle elements overlapping help

### ISSUE THREAD

**Issue by shawntharrin** [Vestride/Shuffle#98]
Hi Glen,

I am currently in the process of implementing your shuffle plug-in into my portfolio website. I am having trouble with the different elements within the grid not overlapping each other. When I load the page on the browser, sometimes all of boxes shift up, overlapping each other, vertically. Sometimes when I reload the page or resize the page, however, everything looks fine and is working. I am pretty inexperienced with coding so I could really use any sort of guidance.

When it comes to positioning, the ".project_btn" class (or the class containing the elements/images that are shuffling) need to size in percentage with the width of the users browser window).

I attached a .zip folder with all of the files used on the website along with screenshots of what it should and should not look like.

Thank you for any help! It is extremely appreciated as I have been driving myself crazy with countless hours trying to fix this.

Shawn

![screen shot 2016-03-28 at 4 30 32 pm](https://cloud.githubusercontent.com/assets/18154552/14127878/11c4a142-f5e1-11e5-8237-ce21d6b12b80.png)
![screen shot 2016-03-28 at 4 31 06 pm](https://cloud.githubusercontent.com/assets/18154552/14127877/11c1d976-f5e1-11e5-835f-989b4413dd46.png)
[demo_suffle_help.zip](https://github.com/Vestride/Shuffle/files/194507/demo_suffle_help.zip)

**Comment by Vestride** [comment]
Please check issue #97

**Comment by shawntharrin** [comment]
After adding the "padding-bottom" to the project button, it now keeps the boxes from overlapping, but now depending on how it loads, it either works fine or there is a giant space between the boxes. I think the extra gap (that's equal height to the heights of the boxes) happens when the images load properly before the code.

Any idea why this is now happening?

**Comment by Vestride** [comment]
Here is how I recommend you wrap your images:

```css
.aspect {
  position: relative;
  width: 100%;
  height: 0;
  padding-bottom: 100%;
  overflow: hidden;
}

.aspect__inner {
  position: absolute;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
}

.aspect--16x9 {
  padding-bottom: 56.25%;
}

/* Add more aspect ratios here if you need them */
```

```html
<div class="aspect aspect--16x9">
  <div class="aspect__inner">
    <img src="foo.jpg" alt="a foo">
  </div>
</div>
```

Doing this will make your layout independent of the size of your images.

**Comment by shawntharrin** [comment]
Damn, this isn't working for me either. I even tried laying out the html and css word-for-word from what you have shown in your response. The result when I do this leaves everything blank, and I can't see any of the images.

Perhaps looking at how I have it setup in the files I attached to the previous comment would help? Sorry for being a hassle. I do really appreciate this.

**Comment by Vestride** [comment]
I downloaded your code and ran it in Chrome and it works for me above 1000px. You have a media query set on your stylesheet which makes it apply to only 1000px and up.

```html
<link rel="stylesheet" type="text/css" media="(min-width: 1000px)" href="css/stylesheet_large.css"/>
```

---

This is completely separate from Shuffle, but I wanted to point out a couple things in your code.

* You're using classes, for example `.project_info_wrapper8`, but project info wrappers 1 through 9 use the exact same styles. You can add `class="project_info_wrapper"` to any element and it will have those styles applied to it; you don't need to create a separate class for each item.
* Using classes in CSS will help you reuse code. So instead of:
  ```css
  #mol-prof {
    display: none;
    width: 600px;
    height: 456px;
  }

  #mol-dig {
    display: none;
    width: 600px;
    height: 456px;
  }
  ```
  You can have one class which does the same thing, but you only have to define it once. And if something needs to change, you don't have to change it in many different locations:
  ```css
  .mol-image {
    display: none;
    width: 600px;
    height: 456px;
  }
  ```
  If you still wanted to use IDs, you should group them like this:
  ```css
  #mol-prof,
  #mol-dig {
    display: none;
    width: 600px;
    height: 456px;
  }
  ```
* In your JS, you have a lot of scroll listeners (e.g. `$(window).scroll(...)`). Instead of creating more scroll listeners, you should do all the work you can inside one listener. That doesn't mean all your code has to be in one function though. For example:
  ```js
  $(window).scroll(function(){
    if($(this).scrollTop() > 1500){
      $('.intro_wrapper').css({'opacity': '0'});
    }
  });
  
  $(window).scroll(function(){
    if($(this).scrollTop() < 1500){
      $('.intro_wrapper').css({'opacity': '1'});
    }
  });
  ```
  Could be
  ```js
  $(window).on('scroll', function () {
    var scrollTop = $(window).scrollTop();
    var $introWrapper = $('.intro_wrapper');

    var newOpacity;
    if (scrollTop > 1500) {
      newOpacity = 0;
    } else {
      newOpacity = 1;
    }

    $introWrapper.css({ opacity: newOpacity });
  });
  ```
